### PR TITLE
Encryption streams

### PR DESCRIPTION
**Pull request by Gonyoda**
An effort to reduce memory usage when uploading or download files.  Stop using MemoryStream/byte[] and instead use a temporary file stream.  The temporary files are automatically closed when the stream is closed/disposed.

Can resolve issue https://github.com/snowflakedb/snowflake-connector-net/issues/621

### CODE REVIEW

**Comment by Gonyoda** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sfc-gh-igarish** [comment]
@Gonyoda Thanks for your contribution. Did you get a chance to check performance difference byte[] v/s temp file stream?

**Comment by Gonyoda** [comment]
@sfc-gh-igarish There are 2 aspects of performance, so I'll try to answer both using BenchmarkDotNet.

I created [a project](https://github.com/Snagajob/snowflake-connector-net/blob/benchmarks/Snowflake.Data.Benchmarks/EncryptionStreamBenchmark.cs) that runs a benchmark for the memory stream (old) and the file stream (this PR).  I was not able to run both benchmarks simultaneously, I just switched between the two branches and commented out the benchmark that wouldn't compile.  I ran the benchmarks with a few different file sizes - small, medium and large.  We often load files between medium and large.

I merged the results below:

```
100,000 bytes
|          Method |     Mean |     Error |    StdDev |     Gen0 |     Gen1 |     Gen2 | Allocated |
|---------------- |---------:|----------:|----------:|---------:|---------:|---------:|----------:|
|   RunFileStream | 10.77 ms | 0.1470 ms | 0.1310 ms |  15.6250 |  15.6250 |  15.6250 | 110.46 KB |
| RunMemoryStream | 5.551 ms | 0.0878 ms | 0.0822 ms | 500.0000 | 500.0000 | 500.0000 |   1.72 MB |


10,000,000 bytes
|          Method |     Mean |    Error |   StdDev |      Gen0 |      Gen1 |      Gen2 | Allocated |
|---------------- |---------:|---------:|---------:|----------:|----------:|----------:|----------:|
| RunFileStream   | 46.18 ms | 0.899 ms | 1.503 ms |  333.3333 |  333.3333 |  333.3333 |   9.58 MB |
| RunMemoryStream | 39.81 ms | 0.789 ms | 1.025 ms | 1875.0000 | 1875.0000 | 1875.0000 |  92.76 MB |

220,000,000 bytes
|          Method |      Mean |    Error |    StdDev |   Median |      Gen0 |      Gen1 |      Gen2 | Allocated |
|---------------- |----------:|---------:|----------:|---------:|----------:|----------:|----------:|----------:|
|   RunFileStream | 1036.0 ms | 69.70 ms | 205.40 ms |          |           |           |           | 209.95 MB |
| RunMemoryStream |  935.4 ms | 18.35 ms |  51.46 ms | 918.0 ms | 2000.0000 | 2000.0000 | 2000.0000 |    1.6 GB |

```
 
Conclusion:
No doubt the file-writing is a bit slower than in-memory buffers, but it's not significantly slower.  However, it should be plain to see that the original memory stream uses significantly more memory, especially for large files.

**Comment by sfc-gh-pbulawa** [comment]
Thank you for your contribution. The issue has been addressed within PR #734.

**Pull request closed without merging**
