### PR TITLE
SNOW-172987 - COPY INTO error

### PR DESCRIPTION
**Pull request by SimbaGithub**
Copy into advance the cursor to get the row update information but does not rewind the cursor breaking result set retrieval afterwards.

### CODE REVIEW

**Review by sfc-gh-hyu — COMMENTED** [review]
Can you add a test?

**Comment by alexrosenfeld10** [comment]
as a user, I'm curious what the impact of this bug in existing state is? Please inform.

**Comment by SimbaGithub** [comment]
Good point @sfc-gh-hyu, I have added a test for executing COPY INTO as query and reading the first row. The existing test was only executing COPY INTO as DML.

@alexrosenfeld10 : The issue here is that when trying to read data from a COPY INTO result set (ExecuteReader instead of ExecuteNonQuery), it would fail because the cursor was moved after the first and only row to get the data in the "rows_loaded" cell and use it for the update count.

**Comment by alexrosenfeld10** [comment]
Ah, ok. So the actual copying of the data is bug-free. Great, thanks

**Review by sfc-gh-hyu — APPROVED** [review]

**Pull request merged**
