### PR TITLE
Prevent memory leaks due to expired certs

### PR DESCRIPTION
**Pull request by alexrosenfeld10**
See https://github.com/dotnet/core/issues/6229 and https://github.com/newrelic/newrelic-dotnet-agent/issues/544

@SimbaGithub This should probably be released ASAP, it has a pretty devastating impact and is really hard to debug.

### CODE REVIEW

**Comment by alexrosenfeld10** [comment]
@SimbaGithub @sfc-gh-hyu this _also_ caused a sev1 for us. Can we please get this merged?

**Comment by alexrosenfeld10** [comment]
revert was only to keep diffs clean... mixed a few things up with my internal private fork.

**Comment by sfc-gh-hyu** [comment]
cc @sfc-gh-hchaturvedi It seems that revocation list check leaks certs.

**Comment by alexrosenfeld10** [comment]
Not sure what you mean by "leaks certs". It's a memory leak, and it's in .NET itself. Check dotnet/runtime#52577

**Comment by sfc-gh-hyu** [comment]
Ah I see, sorry I misread. Reading the original thread now :)

**Comment by alexrosenfeld10** [comment]
@sfc-gh-hyu for further context, please read https://github.com/newrelic/newrelic-dotnet-agent/issues/544

**Comment by alexrosenfeld10** [comment]
seems like this was resolved in https://github.com/snowflakedb/snowflake-connector-net/pull/328, closing to clean up the dead PR for the repo maintainers :)

**Pull request closed without merging**
