### PR TITLE
Issue #469 Put fixes

### PR DESCRIPTION
**Pull request by lovalvob**
Fixes multiple bugs with the PUT command.  There are 7 small commits in the branch.  Each is separate, but builds upon those prior.  Reading them from the oldest to newest, it should be pretty clear.  If not, please LMK.

I'm trying to use PUT with pre-gzipped files, and process the server response. Without these fixes, it's not possible.  Here's the list

From the issue that I created:
Put command has several problems:

Put and Get commands should be case insensitive
Put and Get commands fail in asynchronous execute with a unclear error (because they are not supported)
Put fails to properly determine existing compression, and then fails to properly put the file to the server
When a file is 'put', the server response is mapped to incorrect fields in the result. This renders the result unusable.

### CODE REVIEW

**Comment by lovalvob** [comment]
How does one request that check workflows be run?  As a first-time contributor, my pull request is awaiting checks.

**Comment by lovalvob** [comment]
Unfortunately, this is now a bit old.  It may be a pain to merge.  I'm happy to re-implement it against the current main branch if that would be helpful.

**Comment by sfc-gh-igarish** [comment]
@lovalvob Please try to resolve conflicts and see whether it's complex or not. Otherwise as you suggest create a new branch and do your changes. please add me as reviewer and we can go from there. Sorry you have to go through delays.

**Comment by lovalvob** [comment]
I'll try to get to it this weekend.  Thank you for your help.

**Comment by lovalvob** [comment]
Rather than trying to resolve, I started over from the latest version of master.  It's a new pull request #547.
@sfc-gh-igarish I tried to add you as a reviewer, but I need write access for that, apparently.  It could also be my lack of experience with github.  My apologies.

**Comment by lovalvob** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by sfc-gh-igarish — APPROVED** [review]
LGTM

**Comment by lovalvob** [comment]
@sfc-gh-igarish, would you mind approving #547 instead.  It does not need any resolution.

**Comment by sfc-gh-igarish** [comment]
Please close this one, if it's duplicate of 547 PR.

**Pull request closed without merging**
