### PR TITLE
Use GCS access token for upload/download

### PR DESCRIPTION
**Pull request by sfc-gh-ext-simba-lf**
Regarding issue 92

Support using GCS access token for PUT/GET queries

### CODE REVIEW

**Review by sfc-gh-igarish — COMMENTED** [review]
Did you test using GCS downscope token as other driver?

**Comment by sfc-gh-ext-simba-lf** [comment]
> Did you test using GCS downscope token as other driver?

I'll add a test case similar to the other drivers

**Comment by sfc-gh-ext-simba-lf** [comment]
I added two test cases similar to the ODBC and the JDBC connector

The first test case based on ODBC is about executing a large query with the GCS downscoped token: https://github.com/snowflakedb/snowflake-odbc/pull/409/files#diff-9c59c382829b5ea28ce41ba69e6a64bd9e13bd29a1197f2c996710a68fc87976R2576

The second test case based on JDBC uploads and downloads a file with the GCS downscoped token: https://github.com/snowflakedb/snowflake-jdbc/pull/409/files#diff-65666f89fd973572d96644d93d201eeb917372a9cbab1519ab487a9561c5a063R753

**Review by sfc-gh-igarish — APPROVED** [review]
Thanks for adding test cases. LGTM

**Pull request merged**
