### PR TITLE
SnowflakeDbConnectionPool - Public not internal

### LINKED ISSUE #481: Cannot configure connections pool as SnowflakeDbConnectionPool class has internal access modifier
### Issue description
According to documentation 
https://github.com/snowflakedb/snowflake-connector-net#using-connection-pools
it should be possible to configure connection pool.
But since the class SnowflakeDbConnectionPool is internal - the class is not visible to code of an application.

### Configuration
Driver version: 2.0.14

### PR DESCRIPTION
**Pull request by lee-chrisbell**
SnowflakeDbConnectionPool should be public to perform configuration tasks

closes #481

### CODE REVIEW

**Comment by balakrishnanj** [comment]
@lee-chrisbell any plans to merge this PR?

**Comment by scastria** [comment]
I also need this PR

**Comment by lee-chrisbell** [comment]
> @lee-chrisbell any plans to merge this PR?

I hope so! I still need reviewers, though

**Review by sfc-gh-igarish — APPROVED** [review]
Looks good to me.

**Review by sfc-gh-shickey — APPROVED** [review]
Reviewed and approved by Ilesh Garish

**Review by sfc-gh-igarish — APPROVED** [review]

**Review by sfc-gh-igarish — APPROVED** [review]

**Review by sfc-gh-igarish — APPROVED** [review]
Looks good to me.

**Comment by sfc-gh-hchaturvedi** [comment]
Proxying approval for @sfc-gh-igarish

**Review by sfc-gh-hchaturvedi — APPROVED** [review]
proxying approval for Ilesh.

**Pull request merged**
