### PR TITLE
Fixes to PUT implementation

### PR DESCRIPTION
**Pull request by lovalvob**
Fixes multiple bugs with the PUT command. There are 6 small commits in the branch. Each is separate, but builds upon those prior. Reading them from the oldest to newest, it should be pretty clear. If not, please LMK.

I'm trying to use PUT with pre-gzipped files, and process the server response. Without these fixes, it's not possible. Here's the list

From the issue that I created: #469 
Put command has several problems:

Put and Get commands should be case insensitive
Put and Get commands fail in asynchronous execute with a unclear error (because they are not supported)
Put fails to properly determine existing compression, and then fails to properly put the file to the server
When a file is 'put', the server response is mapped to incorrect fields in the result. This renders the result unusable.

### CODE REVIEW

**Comment by lovalvob** [comment]
This is a replacement for PR #470.  That PR got old, and rather than resolve the issues, I simply started over from the latest master.  @sfc-gh-igarish . I'm sorry that I wasn't able to add you as a reviewer.  I seem to lack that permission.  Alternatively, it could be my lack of experience with github.

**Comment by lovalvob** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lovalvob** [comment]
recheck

**Comment by lovalvob** [comment]
@sfc-gh-igarish, Can you help me work through the automated checks.  They appear to be failing on parameters.  I suspect that there's a guide somewhere.  Can you direct me?

**Comment by sfc-gh-igarish** [comment]
Still PR is a Draft. Can you make it real review? Then I can try to get your PR and see I can tigger the merge gates again.

**Comment by lovalvob** [comment]
recheck

**Comment by lovalvob** [comment]
Done, and thanks.

Barry

**Comment by SimbaGithub** [comment]
PR is now merged through this PR: https://github.com/snowflakedb/snowflake-connector-net/pull/556

**Pull request closed without merging**
