### PR TITLE
SNOW-165479 - Use Task.Delay instead of Thread.Sleep in the Async method.

### PR DESCRIPTION
**Pull request by akrock**
Use Task.Delay instead of Thread.Sleep in the Async method.

Addresses #213 SNOW-165479: Blocking thread on retry handler

### CODE REVIEW

**Comment by extremeandy** [comment]
LGTM 👍

**Comment by icambron** [comment]
This really needs to be merged. You can't block async threads like this.

**Comment by extremeandy** [comment]
It's because of things like this that we end up just maintaining our own fork 🤷‍♂️

**Comment by akrock** [comment]
@extremeandy I know right, we have never been on the official snowflake build over the last 3-4 years, but recently It's gotten so bad I have literally thought about making our fork an "unofficial" one and actually putting it up in Nugets.

This is the branch we are actively running in production (that includes this fix and some others).
https://github.com/akrock/snowflake-connector-net/tree/pc-master-2020
NOTE: I haven't synced it up in about a year, but it is stable for our usage (probably about 1million daily queries). 

I will look to picking up some more of the active PRs and other changes when I can work it into a sprint in the next few weeks. If there is community interest in an "unofficial" fork at that point I might be able to invest a little extra time to get  CI & a package setup.

**Comment by extremeandy** [comment]
I've considered switching over to using this package but I'm not sure how mature it is, and the lack of support for chunks could be an issue:

https://github.com/fixer-m/snowflake-db-net-client/issues

**Comment by akrock** [comment]
Nice I wasn't aware of that one, I will keep an eye on it. Unfortunately not having support for chunks will be a deal breaker us.

**Comment by icambron** [comment]
We also keep a fork and sync it up every once in a while. It's frustrating. At some point one of us will have to publish or we're all doing the same work independently

**Comment by stegus64** [comment]
@SimbaGithub This seems like something you should really merge as soon as possible.

**Comment by SimbaGithub** [comment]
@akrock Do you mind resolving conflicts with master so that I can approve this and merge?
Otherwise, I can just create new PR if that's easier for you.

**Comment by akrock** [comment]
@SimbaGithub it's updated

**Comment by SimbaGithub** [comment]
Awesome, thank you @akrock! 
Will merge right now.

**Review by SimbaGithub — APPROVED** [review]

**Pull request merged**
