### PR TITLE
Add support for new OKTA OIE to .NET Driver

### PR DESCRIPTION
**Pull request by sfc-gh-ext-simba-lf**
Regarding https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/72

Use the session token if it exists instead of the cookie token for the one time token

### CODE REVIEW

**Review by sfc-gh-igarish — COMMENTED** [review]
did you test using OIE setup of Joyce?

**Comment by sfc-gh-ext-simba-lf** [comment]
> did you test using OIE setup of Joyce?

We're currently doing tests with that OIE setup

**Review by sfc-gh-igarish — APPROVED** [review]
LGTM. Please merge after testing OIE.

**Comment by sfc-gh-ext-simba-lf** [comment]
> LGTM. Please merge after testing OIE.

Confirmed .NET can successfully connect through Okta

**Pull request merged**
