### PR TITLE
Prevent SnowflakeDbConnection.AsyncOpen from blocking Close request

### PR DESCRIPTION
**Pull request by tdg5**
Similar to the code that already exists in the synchronous version of `Open`, add some error handling to make sure the DbConnection doesn't end up in a weird state where it will block forever when `Close`  or `Dispose` is called.

### CODE REVIEW

**Comment by alexrosenfeld10** [comment]
@sfc-gh-stakeda tagging you here too for visibility. It would be nice to get this reviewed

**Comment by sfc-gh-stakeda** [comment]
Can you include the test case?

**Comment by hellooperatorpatchmethrough** [comment]
We would like this to be merged in asap. 
Is there anything we do to speed up the process?

**Comment by sfc-gh-stakeda** [comment]
Forwarded the message to a new dev team.

**Comment by dnawnOlo** [comment]
I'm also running into this issue. In our case we had a network issue that prevented connecting to Snowflake. Since we are using OpenAsync(), the current code sets the connection state to open even though it failed to connect. When SnowflakeDbConnection is disposed of and SfSession.close() is called, ultimately RestRequester.Post() is called and the PostAsync call made in the Task.Run throws an AggregateException and crashes our w3wp process. Switching over to using Open() in the interim, but is there any plan or update on getting this merged in?

**Comment by sfc-gh-igarish** [comment]
@tdg5 Could you please resolve conflicts? Are you still interested in this PR? If not, could you please close it?

**Comment by sfc-gh-igarish** [comment]
Closing this old PR. Please reopen if needed.

**Pull request closed without merging**
